### ISSUE TITLE
400 Error on posting events

### ISSUE THREAD

**Issue by kmeleon1982** [lion123dev/hx-game-analytics#1]
I'm unable to figure out how/if this works. Using sandbox keys I keep getting a 400 error if I call StartPosting().
Am I missing something? Maybe a simple example of what I should call to have something appear in the dashboard?

**Comment by lion123dev** [comment]
A simple example is available at https://github.com/lion123dev/hx-game-analytics/blob/documentation/README.md
Let me know if it works for you. If not, post some more info here: target, code, what events you are sending, etc.

**Comment by kmeleon1982** [comment]
This is the code I have: http://pastebin.com/zfHQdPN6
I modified onSubmitFailed(reason:String) in GameAnalytics.hx:
public dynamic function OnSubmitFail(reason:String):Void
    {
        trace ("Submit Failed -> " + Json.stringify(reason));
    }
And that gives me
 Submit Failed -> "Http Error #400"

**Comment by lion123dev** [comment]
Game Analytics have very strict validation rules:

```
os_version: ^(ios|android|windows|windows_phone|blackberry|roku|tizen|nacl|mac_osx|webplayer) [0-9]{0,5}(\\.[0-9]{0,5}){0,2}$
platform: ["ios", "android", "windows", "windows_phone", "blackberry", "roku", "tizen", "nacl", "mac_osx", "webplayer"] (should be one of those)
```

And unknown Identifier FlowType is probably because you didn't import it. If on FlashDevelop, click on it and Ctrl+Shift+F1.

**Comment by kmeleon1982** [comment]
Using : 
ga.Init(success, fail, "windows", "windows", "unknown", "Manufacturer");

Still getting the 400 error. I am trying the windows export in FD. (the flash export fails to build)

I'm trying to use your package in the stencyl engine, so I manually copied all the files in a custom dir, changed the package line in all those files and removed the tree structure that you had, and in FD I just had to "include src.\* " to access everything. (that removes some package issues from Stencyl)
FlowType was showing up in blue in that line, and I could even go to it's declaration with F4, and yet the error was still showing up. (works now after importing the Events file directly).

**Comment by lion123dev** [comment]
Found the bug, will push a fix soon. You can fix it manually in GameAnalytics.hx. Just add this line:

```
_defaultValues.session_num = _storage.sessionNum;
```

Before this one:

```
_defaultValues.session_id = _storage.sessionId;
```

**Comment by kmeleon1982** [comment]
That still gives me the 400 error.

**Comment by kmeleon1982** [comment]
I added a few trace lines in some functions in case the output might be useful:
http://pastebin.com/02iguF5u

**Comment by lion123dev** [comment]
Version is invalid. Change it to "windows 10" or something.

```
os_version: ^(ios|android|windows|windows_phone|blackberry|roku|tizen|nacl|mac_osx|webplayer) [0-9]{0,5}(\\.[0-9]{0,5}){0,2}$
```

You can see a space between os and version, so "windows " will probably pass the validation too.
UPDATE: Just tested. "windows 10" works, "windows " (with a space) works, "windows" doesn't work.

**Comment by kmeleon1982** [comment]
That works. Thanks for the assistance. I'll open new issues if they show up once I start testing on iOS and Android. :+1:
