### ISSUE TITLE
UserID on Android

### ISSUE THREAD

**Issue by andrew-git** [lion123dev/hx-game-analytics#3]
Looks like on every new launch of android app generates new UserID, so no tracking of returning visitors avalable.
Same code shared on all target except flash, so probably other targets have same problems (neko definitely).

Thanks!

**Comment by lion123dev** [comment]
Right now there's no good way to save data across sessions on any other platform than flash without adding dependencies to the project. You'll have to implement your own saving of the userId and pass it to the optional parameter of Init.

**Comment by andrew-git** [comment]
Thanks,
As I understand you don't have dependencies with other frameworks (like OpenFL) and I could use SharedObject from them crossplatform.
How I could generate userId at first launch to store and use?

Maybe better add returning value of userId to Init, to help reuse it?
And when pass userId store it in storage, because now it didn't have setter for userId?

**Comment by lion123dev** [comment]
Decided to go for OpenFL for saving consistent data between sessions, so saving should work now.
